package domain.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import util.common.StringUtility;

/**
 * JPA entity (table: m_user)<br>
 * <p>
 *  The getter, setter, equals, and hashCode methods are automatically 
 *  generated by lombok at compile.
 */
@Entity @Table(name = "m_user")
@Accessors(chain = true) @Getter @Setter @EqualsAndHashCode
public class M_User implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Id @Column(name = "userid", nullable = false, length = 10)
	private String userid;
	
	@Column(name = "username", length = 40)
	private String username;
	
	@Column(name = "password", length = 30)
	private String password;
	
	@Column(name = "enabled", nullable = false, columnDefinition="BIT", length = 1)
	private boolean enabled;
	
	@Column(name = "description", length = 50)
	private String description;
	
	@Override
	public String toString() {
		return StringUtility.toStringForBeans(this);
	}
	
}
