package domain.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import util.common.StringUtility;

/**
 * JPA entity (table: t_task)<br>
 * <p>
 *  The getter, setter, equals, and hashCode methods are automatically 
 *  generated by lombok at compile.
 */
@Entity @Table(name = "t_task")
@Accessors(chain = true) @Getter @Setter @EqualsAndHashCode
public class T_Task implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Id @GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", nullable = false)
	private Integer id;
	
	@Column(name = "title", length = 100)
	private String title;
	
	@Column(name = "scheduledate") @Temporal(TemporalType.DATE)
	private Date scheduledate;
	
	@Column(name = "status", nullable = false, columnDefinition="BIT", length = 1)
	private boolean status;
	
	@Column(name = "description", columnDefinition = "TEXT", length = 65535)
	private String description;
	
	@Column(name = "userid", length = 11)
	private String userid;
	
	@Override
	public String toString() {
		return StringUtility.toStringForBeans(this);
	}
	
}
