package app.form;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.DateTimeFormat;

import domain.validation.DateFormatCheckForString;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import util.common.StringUtility;

/**
 * Form class ("Validation check" screen)<br>
 * <p>
 *  The getter, setter, equals, and hashCode methods are automatically 
 *  generated by lombok at compile.
 */
@Accessors(chain = true) @Getter @Setter @EqualsAndHashCode
public class EmployeeForm implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Size(min = 2, max = 30)
	private String name;
	
	@NotEmpty @Email
	private String email;
	
	@NotNull @Min(18) @Max(110)
	private Integer age;
	
	@Min(10)
	private String phone;
	
	@NotEmpty
	private String gender;
	
	@NotNull @DateTimeFormat(pattern = "yyyy/MM/dd") @Past
	private Date birthday;
	
	@DateFormatCheckForString(format = {"yyyy/MM/dd", "MM/dd/yyyy"})	// Proprietary validation
	private String credit;
	
	public String toString() {
		return StringUtility.toStringForBeans(this);
	}
	
}
