package app.form;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;

import org.springframework.format.annotation.DateTimeFormat;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import util.common.StringUtility;

/**
 * Form class ("Input form" screen)<br>
 * <p>
 *  The getter, setter, equals, and hashCode methods are automatically 
 *  generated by lombok at compile.
 */
@Accessors(chain = true) @Getter @Setter @EqualsAndHashCode
public class InputForm implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private String inputstr;
	
	private Integer inputint;
	
	@NotNull @DateTimeFormat(pattern = "yyyy/MM/dd")
	private Date inputdate;
	
	private String password;
	
	private String textarea;
	
	private String radiobutton;
	
	private String radiobuttons;
	
	private String checkbox;
	
	private boolean checkboxbool;
	
	private String[] checkboxes;
	
	private String[] select;
	
	private String selectoption;
	
	private String hidden;
	
	public String toString() {
		return StringUtility.toStringForBeans(this);
	}
	
}
