package app.form;

import java.io.Serializable;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import util.common.StringUtility;

/**
 * Form class ("Asynchronous (send mail)" screen)<br>
 * <p>
 *  The getter, setter, equals, and hashCode methods are automatically 
 *  generated by lombok at compile.
 */
@Accessors(chain = true) @Getter @Setter @EqualsAndHashCode
public class MailForm 	implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private String from;
	
	private String to;
	
	private String subject;
	
	private String message;
	
	public String toString() {
		return StringUtility.toStringForBeans(this);
	}
	
}
