package app.form;

import java.io.Serializable;
import java.util.List;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import util.common.StringUtility;

/**
 * Form class ("DB paging select" screen)<br>
 * <p>
 *  The getter, setter, equals, and hashCode methods are automatically 
 *  generated by lombok at compile.
 */
@Accessors(chain = true) @Getter @Setter @EqualsAndHashCode
public class TaskPageDto implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private int totalPages;
	
	private int currentPage;
	
	private int pageSize;
	
	private List<TaskForm> tasklist;
	
	private boolean hasNextPage;
	
	private boolean hasPreviousPage;
	
	public String toString() {
		return StringUtility.toStringForBeans(this);
	}
	
}
