package app.form;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.springframework.format.annotation.DateTimeFormat;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import util.common.StringUtility;

/**
 * Form class (DB-CRUD control screens)<br>
 * <p>
 *  The getter, setter, equals, and hashCode methods are automatically 
 *  generated by lombok at compile.
 */
@Accessors(chain = true) @Getter @Setter @EqualsAndHashCode
public class TaskForm implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	
	@Size(min = 2, max = 100)
	private String title;
	
	@NotNull @DateTimeFormat(pattern = "yyyy/MM/dd")
	private Date scheduledate;
	
	@NotNull
	private boolean status;
	
	@NotNull @Size(max = 200)
	private String description;
	
	private String userid;
	
	public String toString() {
		return StringUtility.toStringForBeans(this);
	}
	
}
