package app.form;

import java.io.Serializable;
import java.util.Date;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import util.common.StringUtility;

/**
 * Form class ("Scheduled task history" screen)<br>
 * <p>
 *  The getter, setter, equals, and hashCode methods are automatically 
 *  generated by lombok at compile.
 */
@Accessors(chain = true) @Getter @Setter @EqualsAndHashCode
public class TaskHistoryDto implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	
	private String function;
	
	private String message;
	
	private Date updatedate;
	
	public String toString() {
		return StringUtility.toStringForBeans(this);
	}
	
}
