package com.example.spring.config.security;

import java.util.Collection;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import lombok.Data;

/**
 * Custom UserDetails.<br>
 * Note: See {@link com.example.spring.config here (Chapter 2)} for details.
 */
@Data
public class UserDetailsImpl implements UserDetails {

	private String username;

	private String displayname;

	private String password;

	private boolean enabled;

	private Collection<GrantedAuthority> authorities;

	@SuppressFBWarnings(
			value = "SS_SHOULD_BE_STATIC",
			justification = "static is not required as getters are generated by lombok.")
	private final boolean accountNonExpired = true;

	@SuppressFBWarnings(
			value = "SS_SHOULD_BE_STATIC",
			justification = "static is not required as getters are generated by lombok.")
	private final boolean accountNonLocked = true;

	@SuppressFBWarnings(
			value = "SS_SHOULD_BE_STATIC",
			justification = "static is not required as getters are generated by lombok.")
	private final boolean credentialsNonExpired = true;

	private Integer sessiontimeout;

}
